# Generated by Django 5.1.7 on 2025-03-27 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('total_miles_today', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_mileage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('carrier_name', models.CharField(max_length=255)),
                ('main_office_address', models.TextField()),
                ('truck_number', models.CharField(max_length=50)),
                ('home_terminal_address', models.TextField()),
                ('cycle_type', models.CharField(choices=[('70/8', '70 Hours / 8 Days'), ('60/7', '60 Hours / 7 Days')], default='70/8', max_length=10)),
                ('document_number', models.CharField(blank=True, max_length=50, null=True)),
                ('shipper', models.CharField(blank=True, max_length=255, null=True)),
                ('commodity', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_on_duty_last_period', models.FloatField(default=0.0)),
                ('available_hours_tomorrow', models.FloatField(default=0.0)),
                ('reset_applied', models.BooleanField(default=False)),
                ('consecutive_hours_off', models.FloatField(default=0.0)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recap', to='triplog.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('total_off_duty_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_sleeper_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_driving_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_on_duty_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_on_duty_hours_last_6_days', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_on_duty_hours_last_7_days', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_on_duty_hours_last_8_days', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_on_duty_hours_last_7_days_60', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('available_hours_tomorrow', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_miles_driving_today', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_miles_today', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='triplog.trip')),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty', 'On Duty, Not Driving')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('automated', models.BooleanField(default=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='triplog.triplog')),
            ],
        ),
    ]
