# Generated by Django 5.1.7 on 2025-03-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='status',
        ),
        migrations.AddField(
            model_name='logentry',
            name='end_gps',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='mileage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='logentry',
            name='start_gps',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
