# Generated by Django 5.1.7 on 2025-03-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0002_remove_logentry_status_logentry_end_gps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='status',
            field=models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty', 'On Duty, Not Driving')], default='off_duty', max_length=20),
            preserve_default=False,
        ),
    ]
