# Generated by Django 5.1.7 on 2025-04-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0004_trip_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='triplog',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
